version: "3"
services:
    docsify:

        build:
            context: ./
            dockerfile: docsify.Dockerfile
        volumes:
            - ./:/usr/src
        networks:
            - default
        ports:
            - "${DOCSIFY_PORT}:3000"
networks:
    default:
        external:
            name: testing-cin-network
